# Generated by Django 5.2.1 on 2025-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                (
                    "tipo_pedido",
                    models.CharField(
                        choices=[("recoger", "Recoger"), ("domicilio", "Domicilio")],
                        max_length=10,
                    ),
                ),
                ("direccion", models.TextField(blank=True)),
                ("productos", models.TextField()),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[("efectivo", "Efectivo"), ("tarjeta", "Tarjeta")],
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
